# Site settings
title: Peter Ramsing - Notes from a frontend developer
email: hi@peterramsing.com
baseurl:
url: http://peter.coffee
twitter_username: peterramsing
github_username:  peterramsing
timezone: America/Los_Angeles

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
permalink: none
paginate: 5
paginate_path: "/page:num/"

# Gem
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
